apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choustoulakis-website-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - "choustoulakis.de"
        - "www.choustoulakis.de"
      secretName: choustoulakis-website-tls
  rules:
    - host: choustoulakis.de
      http: &http
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: choustoulakis-website-svc
                port:
                  number: 80
    - host: www.choustoulakis.de
      http: *http
